apiVersion: v1
kind: Service
metadata:
  name: myzipmaster1-ceaee-service
spec:
  type: NodePort
  selector:
    app: myzipmaster1-ceaee
  ports:
    - protocol: TCP
      port: 8197
      targetPort: 8080
